export type ItalyCapoluogo = {
    city: string;
    province: string;
    region: string;
    state: "Italia";
  };
  
  
  export const ITALY_CAPOLUOGHI: ItalyCapoluogo[] = [
    { city: "Roma", province: "RM", region: "Lazio", state: "Italia" },
    { city: "Milano", province: "MI", region: "Lombardia", state: "Italia" },
    { city: "Napoli", province: "NA", region: "Campania", state: "Italia" },
    { city: "Torino", province: "TO", region: "Piemonte", state: "Italia" },
    { city: "Palermo", province: "PA", region: "Sicilia", state: "Italia" },
    { city: "Bologna", province: "BO", region: "Emilia-Romagna", state: "Italia" },
    { city: "Firenze", province: "FI", region: "Toscana", state: "Italia" },
    { city: "Venezia", province: "VE", region: "Veneto", state: "Italia" },
    { city: "Bari", province: "BA", region: "Puglia", state: "Italia" },
  { city: "Brindisi", province: "BR", region: "Puglia", state: "Italia" },
{ city: "Altamura", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Bitonto", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Bitritto", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Capurso", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Casamassima", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Conversano", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Corato", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Gioia del Colle", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Gravina in Puglia", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Locorotondo", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Mola di Bari", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Monopoli", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Noicattaro", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Palo del Colle", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Putignano", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Rutigliano", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Sammichele di Bari", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Turi", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Valenzano", province: "Bari", region: "Puglia", state: "Italia" },
  { city: "Barletta", province: "BAT", region: "Puglia", state: "Italia" },
  { city: "Andria", province: "BAT", region: "Puglia", state: "Italia" },
  { city: "Trani", province: "BAT", region: "Puglia", state: "Italia" },
  { city: "Bisceglie", province: "BAT", region: "Puglia", state: "Italia" },
  { city: "Canosa di Puglia", province: "BAT", region: "Puglia", state: "Italia" },
  { city: "Margherita di Savoia", province: "BAT", region: "Puglia", state: "Italia" },
  { city: "Minervino Murge", province: "BAT", region: "Puglia", state: "Italia" },
  { city: "San Ferdinando di Puglia", province: "BAT", region: "Puglia", state: "Italia" },
  { city: "Spinazzola", province: "BAT", region: "Puglia", state: "Italia" },
  { city: "Trinitapoli", province: "BAT", region: "Puglia", state: "Italia" },
  { city: "Carovigno", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "Ceglie Messapica", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "Fasano", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "Francavilla Fontana", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "Mesagne", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "Ostuni", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "San Donaci", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "San Michele Salentino", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "San Pancrazio Salentino", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "Torchiarolo", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "Villa Castelli", province: "Brindisi", region: "Puglia", state: "Italia" },
  { city: "Foggia", province: "Foggia", region: "Puglia", state: "Italia" },
  { city: "Manfredonia", province: "Foggia", region: "Puglia", state: "Italia" },
  { city: "San Severo", province: "Foggia", region: "Puglia", state: "Italia" },
  { city: "Cerignola", province: "Foggia", region: "Puglia", state: "Italia" },
  { city: "Lucera", province: "Foggia", region: "Puglia", state: "Italia" },
  { city: "Vieste", province: "Foggia", region: "Puglia", state: "Italia" },
  { city: "Peschici", province: "Foggia", region: "Puglia", state: "Italia" },
  { city: "Monte Sant'Angelo", province: "Foggia", region: "Puglia", state: "Italia" },
  { city: "Apricena", province: "Foggia", region: "Puglia", state: "Italia" },
  { city: "Lesina", province: "Foggia", region: "Puglia", state: "Italia" },
  { city: "Lecce", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Acquarica del Capo", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Alessano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Alezio", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Alliste", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Andrano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Aradeo", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Arnesano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Bagnolo del Salento", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Botrugno", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Calimera", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Campi Salentina", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Cannole", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Caprarica di Lecce", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Carmiano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Carpignano Salentino", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Casarano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Castri di Lecce", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Castrignano de' Greci", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Castrignano del Capo", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Cavallino", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Collepasso", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Copertino", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Corigliano d'Otranto", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Corsano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Cursi", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Cutrofiano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Diso", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Gagliano del Capo", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Galatina", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Galatone", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Gallipoli", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Giuggianello", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Giurdignano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Guagnano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Lizzanello", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Maglie", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Martano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Martignano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Matino", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Melendugno", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Melissano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Miggiano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Minervino di Lecce", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Monteroni di Lecce", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Montesano Salentino", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Morciano di Leuca", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Muro Leccese", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Nardò", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Neviano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Nociglia", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Novoli", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Ortelle", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Otranto", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Palmariggi", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Parabita", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Patù", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Poggiardo", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Porto Cesareo", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Presicce-Acquarica", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Racale", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Ruffano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Salice Salentino", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Salve", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "San Cassiano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "San Cesario di Lecce", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "San Donato di Lecce", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Sannicola", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Scorrano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Sogliano Cavour", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Soleto", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Specchia", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Spongano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Squinzano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Sternatia", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Supersano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Surano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Surbo", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Taurisano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Taviano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Tiggiano", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Trepuzzi", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Tricase", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Tuglie", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Ugento", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Uggiano la Chiesa", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Veglie", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Vernole", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Zollino", province: "Lecce", region: "Puglia", state: "Italia" },
  { city: "Taranto", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Avetrana", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Carosino", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Castellaneta", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Crispiano", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Faggiano", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Fragagnano", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Ginosa", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Grottaglie", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Laterza", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Leporano", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Lizzano", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Manduria", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Martina Franca", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Maruggio", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Massafra", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Monteiasi", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Montemesola", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Monteparano", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Mottola", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Palagianello", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Palagiano", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Pulsano", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Roccaforzata", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "San Giorgio Ionico", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "San Marzano di San Giuseppe", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Sava", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Statte", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Torricella", province: "Taranto", region: "Puglia", state: "Italia" },
  { city: "Potenza", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Abriola", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Acerenza", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Albano di Lucania", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Anzi", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Armento", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Atella", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Avigliano", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Balvano", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Banzi", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Baragiano", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Bella", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Brienza", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Brindisi Montagna", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Calvello", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Calvera", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Campomaggiore", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Cancellara", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Carbone", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Castelgrande", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Castelluccio Inferiore", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Castelluccio Superiore", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Castelmezzano", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Castelsaraceno", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Castronuovo di Sant'Andrea", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Cersosimo", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Chiaromonte", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Corleto Perticara", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Episcopia", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Fardella", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Filiano", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Forenza", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Francavilla in Sinni", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Gallicchio", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Genzano di Lucania", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Grumento Nova", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Guardia Perticara", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Lagonegro", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Latronico", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Laurenzana", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Lauria", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Lavello", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Maratea", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Marsico Nuovo", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Marsicovetere", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Maschito", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Melfi", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Missanello", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Molterno", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Montemilone", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Montemurro", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Muro Lucano", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Nemoli", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Noepoli", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Oppido Lucano", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Palazzo San Gervasio", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Pescopagano", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Picerno", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Pietragalla", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Pietrapertosa", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Pignola", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Rapolla", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Rapone", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Rionero in Vulture", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Ripacandida", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Rivello", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Roccanova", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Rotonda", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Ruoti", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Ruvo del Monte", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "San Chirico Nuovo", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "San Chirico Raparo", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "San Costantino Albanese", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "San Fele", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "San Martino d'Agri", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "San Severino Lucano", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Sant'Angelo Le Fratte", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Sant'Arcangelo", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Sarconi", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Sasso di Castalda", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Satriano di Lucania", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Savoia di Lucania", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Senise", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Spinoso", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Teana", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Terranova di Pollino", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Tito", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Tolve", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Tramutola", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Trecchina", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Trivigno", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Vaglio Basilicata", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Venosa", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Vietri di Potenza", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Viggianello", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Viggiano", province: "Potenza", region: "Basilicata", state: "Italia" },
  { city: "Matera", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Accettura", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Aliano", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Bernalda", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Calciano", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Cirigliano", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Colobraro", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Craco", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Ferrandina", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Garaguso", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Gorgoglione", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Grassano", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Grottole", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Irsina", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Miglionico", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Montalbano Jonico", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Montescaglioso", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Nova Siri", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Oliveto Lucano", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Pisticci", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Policoro", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Pomarico", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Rotondella", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Salandra", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "San Giorgio Lucano", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "San Mauro Forte", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Scanzano Jonico", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Stigliano", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Tricarico", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Tursi", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Valsinni", province: "Matera", region: "Basilicata", state: "Italia" },
  { city: "Campobasso", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Acquaviva Collecroce", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Baranello", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Bojano", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Bonefro", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Busso", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Campochiaro", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Campodipietra", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Campolieto", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Campomarino", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Casacalenda", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Casalciprano", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Castelbottaccio", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Castellino del Biferno", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Castelmauro", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Castropignano", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Cercemaggiore", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Cercepiccola", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Civitacampomarano", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Colle d’Anchise", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Colletorto", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Duronia", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Ferrazzano", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Fossalto", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Gambatesa", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Gildone", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Guardialfiera", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Guardiaregia", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Guglionesi", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Jelsi", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Larino", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Limosano", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Lucito", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Lupara", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Macchia Valfortore", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Mafalda", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Matrice", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Mirabello Sannitico", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Molise", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Monacilioni", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Montagano", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Montecilfone", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Montefalcone nel Sannio", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Montelongo", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Montemitro", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Montenero di Bisaccia", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Montorio nei Frentani", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Morrone del Sannio", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Oratino", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Palata", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Petacciato", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Petrella Tifernina", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Pietracatella", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Pietracupa", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Portocannone", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Provvidenti", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Riccia", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Ripabottoni", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Ripalimosani", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Roccavivara", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Rotello", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Salcito", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "San Biase", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "San Felice del Molise", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "San Giacomo degli Schiavoni", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "San Giovanni in Galdo", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "San Giuliano del Sannio", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "San Giuliano di Puglia", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Santa Croce di Magliano", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Sant’Angelo Limosano", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Sepino", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Spinete", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Tavenna", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Termoli", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Torella del Sannio", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Toro", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Trivento", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Ururi", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Vinchiaturo", province: "Campobasso", region: "Molise", state: "Italia" },
  { city: "Isernia", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Agnone", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Bagnoli del Trigno", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Belmonte del Sannio", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Cantalupo nel Sannio", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Capracotta", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Carovilli", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Carpinone", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Castel del Giudice", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Castel San Vincenzo", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Castelpetroso", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Castelpizzuto", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Castelverrino", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Cerro al Volturno", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Chiauci", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Civitanova del Sannio", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Colli a Volturno", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Conca Casale", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Filignano", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Forlì del Sannio", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Fornelli", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Frosolone", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Longano", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Macchia d’Isernia", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Macchiagodena", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Miranda", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Montaquila", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Montenero Val Cocchiara", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Monteroduni", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Pesche", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Pescolanciano", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Pescopennataro", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Pettoranello del Molise", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Pietrabbondante", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Pizzone", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Poggio Sannita", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Pozzilli", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Rionero Sannitico", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Roccamandolfi", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Roccasicura", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Rocchetta a Volturno", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "San Pietro Avellana", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Sant’Agapito", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Santa Maria del Molise", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Sant’Elena Sannita", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Scapoli", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Sessano del Molise", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Sesto Campano", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Vastogirardi", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Venafro", province: "Isernia", region: "Molise", state: "Italia" },
  { city: "Catanzaro", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Albi", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Amaroni", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Amato", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Andali", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Argusto", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Badolato", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Belcastro", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Borgia", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Botricello", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Caraffa di Catanzaro", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Cardinale", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Carlopoli", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Cenadi", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Centrache", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Cerva", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Chiaravalle Centrale", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Cicala", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Conflenti", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Cortale", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Cropani", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Curinga", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Davoli", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Decollatura", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Falerna", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Feroleto Antico", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Fossato Serralta", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Gagliato", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Gasperina", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Gimigliano", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Girifalco", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Guardavalle", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Isca sullo Ionio", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Jacurso", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Lamezia Terme", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Magisano", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Maida", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Marcedusa", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Marcellinara", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Martirano", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Martirano Lombardo", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Miglierina", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Montauro", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Montepaone", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Motta Santa Lucia", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Nocera Terinese", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Olivadi", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Palermiti", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Pentone", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Petrizzi", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Petronà", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Pianopoli", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Platania", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "San Floro", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "San Mango d’Aquino", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "San Pietro a Maida", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "San Pietro Apostolo", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "San Sostene", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Sant’Andrea Apostolo dello Ionio", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Santa Caterina dello Ionio", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Serrastretta", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Settingiano", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Simeri Crichi", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Sorbo San Basile", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Soverato", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Soveria Mannelli", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Soveria Simeri", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Squillace", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Stalettì", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Taverna", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Tiriolo", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Torre di Ruggiero", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Vallefiorita", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Zagarise", province: "Catanzaro", region: "Calabria", state: "Italia" },
  { city: "Crotone", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Belvedere di Spinello", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Caccuri", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Carfizzi", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Casabona", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Castelsilano", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Cerenzia", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Cirò", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Cirò Marina", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Crucoli", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Cutro", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Isola di Capo Rizzuto", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Melissa", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Mesoraca", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Pallagorio", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Petilia Policastro", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Roccabernarda", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Rocca di Neto", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "San Mauro Marchesato", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "San Nicola dell'Alto", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Santa Severina", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Savelli", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Scandale", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Strongoli", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Umbriatico", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Verzino", province: "Crotone", region: "Calabria", state: "Italia" },
  { city: "Vibo Valentia", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Acquaro", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Arena", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Briatico", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Brognaturo", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Capistrano", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Cessaniti", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Dasà", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Dinami", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Drapia", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Fabrizia", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Filadelfia", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Filandari", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Filogaso", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Francavilla Angitola", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Ionadi", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Joppolo", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Limbadi", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Maierato", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Mileto", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Mongiana", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Monterosso Calabro", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Nardodipace", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Nicotera", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Parghelia", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Pizzo", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Pizzoni", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Polia", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Ricadi", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Rombiolo", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "San Calogero", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "San Costantino Calabro", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "San Gregorio d'Ippona", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "San Nicola da Crissa", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Sant'Onofrio", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Serra San Bruno", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Simbario", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Sorianello", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Soriano Calabro", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Spadola", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Spilinga", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Stefanaconi", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Tropea", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Vallelonga", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Vazzano", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Zaccanopoli", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Zambrone", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Zungri", province: "Vibo Valentia", region: "Calabria", state: "Italia" },
  { city: "Reggio Calabria", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Africo", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Agnana Calabra", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Anoia", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Antonimina", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Ardore", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Bagaladi", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Bagnara Calabra", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Benestare", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Bianco", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Bivongi", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Bova", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Bova Marina", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Brancaleone", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Bruzzano Zeffirio", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Calanna", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Camini", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Campo Calabro", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Candidoni", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Canolo", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Caraffa del Bianco", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Cardeto", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Careri", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Casignana", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Caulonia", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Ciminà", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Cinquefrondi", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Cittanova", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Condofuri", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Cosoleto", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Delianuova", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Feroleto della Chiesa", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Ferruzzano", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Fiumara", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Galatro", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Gerace", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Giffone", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Gioia Tauro", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Gioiosa Ionica", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Grotteria", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Laganadi", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Laureana di Borrello", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Locri", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Mammola", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Marina di Gioiosa Ionica", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Maropati", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Martone", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Melicuccà", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Melicucco", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Molochio", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Monasterace", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Montebello Ionico", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Motta San Giovanni", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Oppido Mamertina", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Palizzi", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Palmi", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Pazzano", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Placanica", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Platì", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Polistena", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Portigliola", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Riace", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Rizziconi", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Roccaforte del Greco", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Roccella Ionica", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Roghudi", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Rosarno", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "San Ferdinando", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "San Giorgio Morgeto", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "San Giovanni di Gerace", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "San Lorenzo", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "San Luca", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "San Pietro di Caridà", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "San Procopio", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Sant'Agata del Bianco", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Sant'Alessio in Aspromonte", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Sant'Eufemia d'Aspromonte", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Scido", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Scilla", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Seminara", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Siderno", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Sinopoli", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Staiti", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Stignano", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Stilo", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Taurianova", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Terranova Sappo Minulio", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Varapodio", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Villa San Giovanni", province: "Reggio Calabria", region: "Calabria", state: "Italia" },
  { city: "Cosenza", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Acquaformosa", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Acquappesa", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Acri", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Aiello Calabro", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Aieta", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Albidona", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Alessandria del Carretto", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Altilia", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Altomonte", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Amantea", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Amendolara", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Aprigliano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Belmonte Calabro", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Belsito", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Belvedere Marittimo", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Bianchi", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Bisignano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Bocchigliero", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Bonifati", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Buonvicino", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Calopezzati", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Caloveto", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Campana", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Canna", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Cariati", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Carolei", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Carpanzano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Cassano all'Ionio", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Castiglione Cosentino", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Castrolibero", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Castroregio", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Castrovillari", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Celico", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Cellara", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Cerchiara di Calabria", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Cerisano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Cervicati", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Cerzeto", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Cetraro", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Civita", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Cleto", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Colosimi", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Corigliano-Rossano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Crosia", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Diamante", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Dipignano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Domanico", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Fagnano Castello", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Falconara Albanese", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Figline Vegliaturo", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Firmo", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Fiumefreddo Bruzio", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Francavilla Marittima", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Frascineto", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Fuscaldo", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Grimaldi", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Grisolia", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Guardia Piemontese", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Laino Borgo", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Laino Castello", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Lappano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Lattarico", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Longobardi", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Longobucco", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Lungro", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Luzzi", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Maierà", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Malito", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Mangone", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Marano Marchesato", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Marano Principato", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Marzi", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Mendicino", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Mongrassano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Montalto Uffugo", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Montegiordano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Morano Calabro", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Mormanno", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Mottafollone", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Nocara", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Oriolo", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Orsomarso", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Paola", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Papasidero", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Pedivigliano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Piane Crati", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Pietrafitta", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Pietrapaola", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Plataci", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Praia a Mare", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Rende", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Rocca Imperiale", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Roggiano Gravina", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Rose", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Roseto Capo Spulico", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Rota Greca", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Rovito", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Basile", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Benedetto Ullano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Cosmo Albanese", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Demetrio Corone", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Donato di Ninea", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Fili", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Giorgio Albanese", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Giovanni in Fiore", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Lorenzo Bellizzi", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Lorenzo del Vallo", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Lucido", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Marco Argentano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Martino di Finita", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Nicola Arcella", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Pietro in Amantea", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "San Sosti", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Santa Caterina Albanese", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Santa Domenica Talao", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Sant'Agata di Esaro", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Santo Stefano di Rogliano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Scalea", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Serra d'Aiello", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Spezzano Albanese", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Spezzano della Sila", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Tarsia", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Terranova da Sibari", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Terravecchia", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Torano Castello", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Tortora", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Trebisacce", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Vaccarizzo Albanese", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Verbicaro", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Villapiana", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Zumpano", province: "Cosenza", region: "Calabria", state: "Italia" },
  { city: "Cagliari", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Assemini", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Capoterra", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Decimomannu", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Elmas", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Monserrato", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Pula", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Quartu Sant'Elena", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Quartucciu", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Selargius", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Sestu", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Uta", province: "Cagliari", region: "Sardegna", state: "Italia" },
  { city: "Villa San Pietro", province: "Cagliari", region: "Sardegna", state: "Italia" },
   { city: "Sassari", province: "Sassari", region: "Sardegna", state: "Italia" },
  { city: "Alghero", province: "Sassari", region: "Sardegna", state: "Italia" },
  { city: "Porto Torres", province: "Sassari", region: "Sardegna", state: "Italia" },
  { city: "Ozieri", province: "Sassari", region: "Sardegna", state: "Italia" },
  { city: "Tempio Pausania", province: "Sassari", region: "Sardegna", state: "Italia" },
  { city: "Castelsardo", province: "Sassari", region: "Sardegna", state: "Italia" },
  { city: "Arzachena", province: "Sassari", region: "Sardegna", state: "Italia" },
  { city: "La Maddalena", province: "Sassari", region: "Sardegna", state: "Italia" },
  { city: "Santa Teresa Gallura", province: "Sassari", region: "Sardegna", state: "Italia" },
  { city: "Nuoro", province: "Nuoro", region: "Sardegna", state: "Italia" },
  { city: "Macomer", province: "Nuoro", region: "Sardegna", state: "Italia" },
  { city: "Siniscola", province: "Nuoro", region: "Sardegna", state: "Italia" },
  { city: "Orosei", province: "Nuoro", region: "Sardegna", state: "Italia" },
  { city: "Dorgali", province: "Nuoro", region: "Sardegna", state: "Italia" },
  { city: "Orgosolo", province: "Nuoro", region: "Sardegna", state: "Italia" },
  { city: "Mamoiada", province: "Nuoro", region: "Sardegna", state: "Italia" },
  { city: "Oristano", province: "Oristano", region: "Sardegna", state: "Italia" },
  { city: "Cabras", province: "Oristano", region: "Sardegna", state: "Italia" },
  { city: "Ghilarza", province: "Oristano", region: "Sardegna", state: "Italia" },
  { city: "Bosa", province: "Oristano", region: "Sardegna", state: "Italia" },
  { city: "Terralba", province: "Oristano", region: "Sardegna", state: "Italia" },
  { city: "Arborea", province: "Oristano", region: "Sardegna", state: "Italia" },
  { city: "Carbonia", province: "Sud Sardegna", region: "Sardegna", state: "Italia" },
  { city: "Iglesias", province: "Sud Sardegna", region: "Sardegna", state: "Italia" },
  { city: "Sanluri", province: "Sud Sardegna", region: "Sardegna", state: "Italia" },
  { city: "Villacidro", province: "Sud Sardegna", region: "Sardegna", state: "Italia" },
  { city: "Guspini", province: "Sud Sardegna", region: "Sardegna", state: "Italia" },
  { city: "Muravera", province: "Sud Sardegna", region: "Sardegna", state: "Italia" },
  { city: "Sant'Antioco", province: "Sud Sardegna", region: "Sardegna", state: "Italia" },
  { city: "Carloforte", province: "Sud Sardegna", region: "Sardegna", state: "Italia" },
];
